/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-07-29 at 16:12:15 UTC 
 * Modify at your own risk.
 */

package sandtrucks.android.apps.avasthi.com.sandTrucksSystemApi.model;

/**
 * Model definition for SandTrucksManagerBackendApiResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the sandTrucksSystemApi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SandTrucksManagerBackendApiResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer code;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean status;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getCode() {
    return code;
  }

  /**
   * @param code code or {@code null} for none
   */
  public SandTrucksManagerBackendApiResponse setCode(java.lang.Integer code) {
    this.code = code;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public SandTrucksManagerBackendApiResponse setStatus(java.lang.Boolean status) {
    this.status = status;
    return this;
  }

  @Override
  public SandTrucksManagerBackendApiResponse set(String fieldName, Object value) {
    return (SandTrucksManagerBackendApiResponse) super.set(fieldName, value);
  }

  @Override
  public SandTrucksManagerBackendApiResponse clone() {
    return (SandTrucksManagerBackendApiResponse) super.clone();
  }

}
