/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-07-29 at 16:12:15 UTC 
 * Modify at your own risk.
 */

package sandtrucks.android.apps.avasthi.com.sandTrucksSystemApi;

/**
 * Service definition for SandTrucksSystemApi (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link SandTrucksSystemApiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class SandTrucksSystemApi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the sandTrucksSystemApi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://sand-truck-system-2014.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "sandTrucksSystemApi/v1/doesUserExistAndAssociated/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public SandTrucksSystemApi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  SandTrucksSystemApi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "doesUserExistAndAssociated".
   *
   * This request holds the parameters needed by the sandTrucksSystemApi server.  After setting any
   * optional parameters, call the {@link DoesUserExistAndAssociated#execute()} method to invoke the
   * remote operation.
   *
   * @param email
   * @return the request
   */
  public DoesUserExistAndAssociated doesUserExistAndAssociated(java.lang.String email) throws java.io.IOException {
    DoesUserExistAndAssociated result = new DoesUserExistAndAssociated(email);
    initialize(result);
    return result;
  }

  public class DoesUserExistAndAssociated extends SandTrucksSystemApiRequest<sandtrucks.android.apps.avasthi.com.sandTrucksSystemApi.model.SandTrucksManagerBackendApiResponse> {

    private static final String REST_PATH = "{email}";

    /**
     * Create a request for the method "doesUserExistAndAssociated".
     *
     * This request holds the parameters needed by the the sandTrucksSystemApi server.  After setting
     * any optional parameters, call the {@link DoesUserExistAndAssociated#execute()} method to invoke
     * the remote operation. <p> {@link DoesUserExistAndAssociated#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param email
     * @since 1.13
     */
    protected DoesUserExistAndAssociated(java.lang.String email) {
      super(SandTrucksSystemApi.this, "POST", REST_PATH, null, sandtrucks.android.apps.avasthi.com.sandTrucksSystemApi.model.SandTrucksManagerBackendApiResponse.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
    }

    @Override
    public DoesUserExistAndAssociated setAlt(java.lang.String alt) {
      return (DoesUserExistAndAssociated) super.setAlt(alt);
    }

    @Override
    public DoesUserExistAndAssociated setFields(java.lang.String fields) {
      return (DoesUserExistAndAssociated) super.setFields(fields);
    }

    @Override
    public DoesUserExistAndAssociated setKey(java.lang.String key) {
      return (DoesUserExistAndAssociated) super.setKey(key);
    }

    @Override
    public DoesUserExistAndAssociated setOauthToken(java.lang.String oauthToken) {
      return (DoesUserExistAndAssociated) super.setOauthToken(oauthToken);
    }

    @Override
    public DoesUserExistAndAssociated setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (DoesUserExistAndAssociated) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public DoesUserExistAndAssociated setQuotaUser(java.lang.String quotaUser) {
      return (DoesUserExistAndAssociated) super.setQuotaUser(quotaUser);
    }

    @Override
    public DoesUserExistAndAssociated setUserIp(java.lang.String userIp) {
      return (DoesUserExistAndAssociated) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public DoesUserExistAndAssociated setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @Override
    public DoesUserExistAndAssociated set(String parameterName, Object value) {
      return (DoesUserExistAndAssociated) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link SandTrucksSystemApi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link SandTrucksSystemApi}. */
    @Override
    public SandTrucksSystemApi build() {
      return new SandTrucksSystemApi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link SandTrucksSystemApiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setSandTrucksSystemApiRequestInitializer(
        SandTrucksSystemApiRequestInitializer sandtruckssystemapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(sandtruckssystemapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
