/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-09 17:08:39 UTC)
 * on 2014-07-19 at 19:45:51 UTC 
 * Modify at your own risk.
 */

package com.avasthi.apps.roadconditionsensor.sensorrecordendpoint.model;

/**
 * Model definition for SensorRecord.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the sensorrecordendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SensorRecord extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float accelx;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float accely;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float accelz;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float accuracy;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double altitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float azimuth;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float bearing;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float deltaAccelx;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float deltaAccely;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float deltaAccelz;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double latitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double longitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float mfx;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float mfy;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float mfz;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float pitch;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float roll;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float speed;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime timestamp;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getAccelx() {
    return accelx;
  }

  /**
   * @param accelx accelx or {@code null} for none
   */
  public SensorRecord setAccelx(java.lang.Float accelx) {
    this.accelx = accelx;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getAccely() {
    return accely;
  }

  /**
   * @param accely accely or {@code null} for none
   */
  public SensorRecord setAccely(java.lang.Float accely) {
    this.accely = accely;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getAccelz() {
    return accelz;
  }

  /**
   * @param accelz accelz or {@code null} for none
   */
  public SensorRecord setAccelz(java.lang.Float accelz) {
    this.accelz = accelz;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getAccuracy() {
    return accuracy;
  }

  /**
   * @param accuracy accuracy or {@code null} for none
   */
  public SensorRecord setAccuracy(java.lang.Float accuracy) {
    this.accuracy = accuracy;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getAltitude() {
    return altitude;
  }

  /**
   * @param altitude altitude or {@code null} for none
   */
  public SensorRecord setAltitude(java.lang.Double altitude) {
    this.altitude = altitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getAzimuth() {
    return azimuth;
  }

  /**
   * @param azimuth azimuth or {@code null} for none
   */
  public SensorRecord setAzimuth(java.lang.Float azimuth) {
    this.azimuth = azimuth;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getBearing() {
    return bearing;
  }

  /**
   * @param bearing bearing or {@code null} for none
   */
  public SensorRecord setBearing(java.lang.Float bearing) {
    this.bearing = bearing;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getDeltaAccelx() {
    return deltaAccelx;
  }

  /**
   * @param deltaAccelx deltaAccelx or {@code null} for none
   */
  public SensorRecord setDeltaAccelx(java.lang.Float deltaAccelx) {
    this.deltaAccelx = deltaAccelx;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getDeltaAccely() {
    return deltaAccely;
  }

  /**
   * @param deltaAccely deltaAccely or {@code null} for none
   */
  public SensorRecord setDeltaAccely(java.lang.Float deltaAccely) {
    this.deltaAccely = deltaAccely;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getDeltaAccelz() {
    return deltaAccelz;
  }

  /**
   * @param deltaAccelz deltaAccelz or {@code null} for none
   */
  public SensorRecord setDeltaAccelz(java.lang.Float deltaAccelz) {
    this.deltaAccelz = deltaAccelz;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public SensorRecord setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLatitude() {
    return latitude;
  }

  /**
   * @param latitude latitude or {@code null} for none
   */
  public SensorRecord setLatitude(java.lang.Double latitude) {
    this.latitude = latitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLongitude() {
    return longitude;
  }

  /**
   * @param longitude longitude or {@code null} for none
   */
  public SensorRecord setLongitude(java.lang.Double longitude) {
    this.longitude = longitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getMfx() {
    return mfx;
  }

  /**
   * @param mfx mfx or {@code null} for none
   */
  public SensorRecord setMfx(java.lang.Float mfx) {
    this.mfx = mfx;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getMfy() {
    return mfy;
  }

  /**
   * @param mfy mfy or {@code null} for none
   */
  public SensorRecord setMfy(java.lang.Float mfy) {
    this.mfy = mfy;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getMfz() {
    return mfz;
  }

  /**
   * @param mfz mfz or {@code null} for none
   */
  public SensorRecord setMfz(java.lang.Float mfz) {
    this.mfz = mfz;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getPitch() {
    return pitch;
  }

  /**
   * @param pitch pitch or {@code null} for none
   */
  public SensorRecord setPitch(java.lang.Float pitch) {
    this.pitch = pitch;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getRoll() {
    return roll;
  }

  /**
   * @param roll roll or {@code null} for none
   */
  public SensorRecord setRoll(java.lang.Float roll) {
    this.roll = roll;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getSpeed() {
    return speed;
  }

  /**
   * @param speed speed or {@code null} for none
   */
  public SensorRecord setSpeed(java.lang.Float speed) {
    this.speed = speed;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getTimestamp() {
    return timestamp;
  }

  /**
   * @param timestamp timestamp or {@code null} for none
   */
  public SensorRecord setTimestamp(com.google.api.client.util.DateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  @Override
  public SensorRecord set(String fieldName, Object value) {
    return (SensorRecord) super.set(fieldName, value);
  }

  @Override
  public SensorRecord clone() {
    return (SensorRecord) super.clone();
  }

}
