/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-07-29 at 16:11:55 UTC 
 * Modify at your own risk.
 */

package com.avasthi.apps.android.sandtrucks.businessendpoint;

/**
 * Service definition for Businessendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link BusinessendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Businessendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the businessendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://sand-truck-system-2014.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "businessendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Businessendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Businessendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getBusiness".
   *
   * This request holds the parameters needed by the businessendpoint server.  After setting any
   * optional parameters, call the {@link GetBusiness#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetBusiness getBusiness(java.lang.Long id) throws java.io.IOException {
    GetBusiness result = new GetBusiness(id);
    initialize(result);
    return result;
  }

  public class GetBusiness extends BusinessendpointRequest<com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business> {

    private static final String REST_PATH = "business/{id}";

    /**
     * Create a request for the method "getBusiness".
     *
     * This request holds the parameters needed by the the businessendpoint server.  After setting any
     * optional parameters, call the {@link GetBusiness#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetBusiness#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetBusiness(java.lang.Long id) {
      super(Businessendpoint.this, "GET", REST_PATH, null, com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetBusiness setAlt(java.lang.String alt) {
      return (GetBusiness) super.setAlt(alt);
    }

    @Override
    public GetBusiness setFields(java.lang.String fields) {
      return (GetBusiness) super.setFields(fields);
    }

    @Override
    public GetBusiness setKey(java.lang.String key) {
      return (GetBusiness) super.setKey(key);
    }

    @Override
    public GetBusiness setOauthToken(java.lang.String oauthToken) {
      return (GetBusiness) super.setOauthToken(oauthToken);
    }

    @Override
    public GetBusiness setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetBusiness) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetBusiness setQuotaUser(java.lang.String quotaUser) {
      return (GetBusiness) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetBusiness setUserIp(java.lang.String userIp) {
      return (GetBusiness) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetBusiness setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetBusiness set(String parameterName, Object value) {
      return (GetBusiness) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertBusiness".
   *
   * This request holds the parameters needed by the businessendpoint server.  After setting any
   * optional parameters, call the {@link InsertBusiness#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business}
   * @return the request
   */
  public InsertBusiness insertBusiness(com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business content) throws java.io.IOException {
    InsertBusiness result = new InsertBusiness(content);
    initialize(result);
    return result;
  }

  public class InsertBusiness extends BusinessendpointRequest<com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business> {

    private static final String REST_PATH = "business";

    /**
     * Create a request for the method "insertBusiness".
     *
     * This request holds the parameters needed by the the businessendpoint server.  After setting any
     * optional parameters, call the {@link InsertBusiness#execute()} method to invoke the remote
     * operation. <p> {@link InsertBusiness#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business}
     * @since 1.13
     */
    protected InsertBusiness(com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business content) {
      super(Businessendpoint.this, "POST", REST_PATH, content, com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business.class);
    }

    @Override
    public InsertBusiness setAlt(java.lang.String alt) {
      return (InsertBusiness) super.setAlt(alt);
    }

    @Override
    public InsertBusiness setFields(java.lang.String fields) {
      return (InsertBusiness) super.setFields(fields);
    }

    @Override
    public InsertBusiness setKey(java.lang.String key) {
      return (InsertBusiness) super.setKey(key);
    }

    @Override
    public InsertBusiness setOauthToken(java.lang.String oauthToken) {
      return (InsertBusiness) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertBusiness setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertBusiness) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertBusiness setQuotaUser(java.lang.String quotaUser) {
      return (InsertBusiness) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertBusiness setUserIp(java.lang.String userIp) {
      return (InsertBusiness) super.setUserIp(userIp);
    }

    @Override
    public InsertBusiness set(String parameterName, Object value) {
      return (InsertBusiness) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listBusiness".
   *
   * This request holds the parameters needed by the businessendpoint server.  After setting any
   * optional parameters, call the {@link ListBusiness#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListBusiness listBusiness() throws java.io.IOException {
    ListBusiness result = new ListBusiness();
    initialize(result);
    return result;
  }

  public class ListBusiness extends BusinessendpointRequest<com.avasthi.apps.android.sandtrucks.businessendpoint.model.CollectionResponseBusiness> {

    private static final String REST_PATH = "business";

    /**
     * Create a request for the method "listBusiness".
     *
     * This request holds the parameters needed by the the businessendpoint server.  After setting any
     * optional parameters, call the {@link ListBusiness#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListBusiness#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListBusiness() {
      super(Businessendpoint.this, "GET", REST_PATH, null, com.avasthi.apps.android.sandtrucks.businessendpoint.model.CollectionResponseBusiness.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListBusiness setAlt(java.lang.String alt) {
      return (ListBusiness) super.setAlt(alt);
    }

    @Override
    public ListBusiness setFields(java.lang.String fields) {
      return (ListBusiness) super.setFields(fields);
    }

    @Override
    public ListBusiness setKey(java.lang.String key) {
      return (ListBusiness) super.setKey(key);
    }

    @Override
    public ListBusiness setOauthToken(java.lang.String oauthToken) {
      return (ListBusiness) super.setOauthToken(oauthToken);
    }

    @Override
    public ListBusiness setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListBusiness) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListBusiness setQuotaUser(java.lang.String quotaUser) {
      return (ListBusiness) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListBusiness setUserIp(java.lang.String userIp) {
      return (ListBusiness) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListBusiness setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListBusiness setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListBusiness set(String parameterName, Object value) {
      return (ListBusiness) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeBusiness".
   *
   * This request holds the parameters needed by the businessendpoint server.  After setting any
   * optional parameters, call the {@link RemoveBusiness#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveBusiness removeBusiness(java.lang.Long id) throws java.io.IOException {
    RemoveBusiness result = new RemoveBusiness(id);
    initialize(result);
    return result;
  }

  public class RemoveBusiness extends BusinessendpointRequest<Void> {

    private static final String REST_PATH = "business/{id}";

    /**
     * Create a request for the method "removeBusiness".
     *
     * This request holds the parameters needed by the the businessendpoint server.  After setting any
     * optional parameters, call the {@link RemoveBusiness#execute()} method to invoke the remote
     * operation. <p> {@link RemoveBusiness#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveBusiness(java.lang.Long id) {
      super(Businessendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveBusiness setAlt(java.lang.String alt) {
      return (RemoveBusiness) super.setAlt(alt);
    }

    @Override
    public RemoveBusiness setFields(java.lang.String fields) {
      return (RemoveBusiness) super.setFields(fields);
    }

    @Override
    public RemoveBusiness setKey(java.lang.String key) {
      return (RemoveBusiness) super.setKey(key);
    }

    @Override
    public RemoveBusiness setOauthToken(java.lang.String oauthToken) {
      return (RemoveBusiness) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveBusiness setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveBusiness) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveBusiness setQuotaUser(java.lang.String quotaUser) {
      return (RemoveBusiness) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveBusiness setUserIp(java.lang.String userIp) {
      return (RemoveBusiness) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveBusiness setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveBusiness set(String parameterName, Object value) {
      return (RemoveBusiness) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateBusiness".
   *
   * This request holds the parameters needed by the businessendpoint server.  After setting any
   * optional parameters, call the {@link UpdateBusiness#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business}
   * @return the request
   */
  public UpdateBusiness updateBusiness(com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business content) throws java.io.IOException {
    UpdateBusiness result = new UpdateBusiness(content);
    initialize(result);
    return result;
  }

  public class UpdateBusiness extends BusinessendpointRequest<com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business> {

    private static final String REST_PATH = "business";

    /**
     * Create a request for the method "updateBusiness".
     *
     * This request holds the parameters needed by the the businessendpoint server.  After setting any
     * optional parameters, call the {@link UpdateBusiness#execute()} method to invoke the remote
     * operation. <p> {@link UpdateBusiness#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business}
     * @since 1.13
     */
    protected UpdateBusiness(com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business content) {
      super(Businessendpoint.this, "PUT", REST_PATH, content, com.avasthi.apps.android.sandtrucks.businessendpoint.model.Business.class);
    }

    @Override
    public UpdateBusiness setAlt(java.lang.String alt) {
      return (UpdateBusiness) super.setAlt(alt);
    }

    @Override
    public UpdateBusiness setFields(java.lang.String fields) {
      return (UpdateBusiness) super.setFields(fields);
    }

    @Override
    public UpdateBusiness setKey(java.lang.String key) {
      return (UpdateBusiness) super.setKey(key);
    }

    @Override
    public UpdateBusiness setOauthToken(java.lang.String oauthToken) {
      return (UpdateBusiness) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateBusiness setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateBusiness) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateBusiness setQuotaUser(java.lang.String quotaUser) {
      return (UpdateBusiness) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateBusiness setUserIp(java.lang.String userIp) {
      return (UpdateBusiness) super.setUserIp(userIp);
    }

    @Override
    public UpdateBusiness set(String parameterName, Object value) {
      return (UpdateBusiness) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Businessendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Businessendpoint}. */
    @Override
    public Businessendpoint build() {
      return new Businessendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link BusinessendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setBusinessendpointRequestInitializer(
        BusinessendpointRequestInitializer businessendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(businessendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
